### ISSUE TITLE
❓[Help]: FIleMonitor Plugin Woes - directory does not exist (Docker on Linux host)

### ISSUE THREAD

**Issue by xstrex** [David-Maisonave/Axter-Stash#13]
### Please enter a clear and concise detailed question.

Hi, can't get the file monitor plugin to work properly. 

docker-compose
```yaml
  stash:
    container_name: stash
    restart: unless-stopped
    image: stashapp/stash:latest
    network_mode: bridge
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    ports:
      - "9999:9999"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/stash/config:/root/.stash
      - /media/video/adult:/data
      - /opt/docker/stash/metadata:/metadata
      - /opt/docker/stash/cache:/cache
      - /opt/docker/stash/blobs:/blobs
      - /opt/docker/stash/generated:/generated
 ```

"dockers": config
```json
         {"GQL":"http://localhost:9994", "apiKey":"redacted", "bindMounts":[
                 {"/media/video/adult/clips":"/data/clips"},
                 {"/media/video/adult/movies":"/data/movie"},                                                                                                      
             ]
          },
```

Error:
```
[LN:193] INF: This Stash instance GQL = http://192.168.2.7:9999
[LN:293] INF: Adding to scheduler task 'Auto Tag' (weekly) every monday,tuesday,wednesday,thursday,friday,saturday,sunday at 05:00
[LN:291] INF: Adding to scheduler task 'pathParser->Create Tags' (weekly) every day at 05:30
[LN:293] INF: Adding to scheduler task 'Optimise Database' (weekly) every monday,tuesday,wednesday,thursday,friday at 07:00
[LN:293] INF: Adding to scheduler task 'Backup' (weekly) every saturday at 01:00
[LN:293] INF: Adding to scheduler task 'Scan' (weekly) every saturday at 02:30
[LN:293] INF: Adding to scheduler task 'Auto Tag' (weekly) every saturday at 03:00
[LN:293] INF: Adding to scheduler task 'Generate' (weekly) every saturday at 03:30
[LN:293] INF: Adding to scheduler task 'Generate Phashes' (weekly) every saturday at 04:00
[LN:293] INF: Adding to scheduler task 'Clean' (weekly) every saturday at 04:30
[LN:293] INF: Adding to scheduler task 'Clean Generated Files' (weekly) every saturday at 05:00
[LN:293] INF: Adding to scheduler task 'Optimise Database' (weekly) every saturday at 05:30
[LN:293] INF: Adding to scheduler task 'DupFileManager->tag_duplicates_task' (weekly) every sunday at 02:30
[LN:293] INF: Adding to scheduler task 'DupFileManager->Delete Tagged Duplicates' (weekly) every saturday at 02:30
[LN:264] INF: Adding to scheduler task 'CheckStashIsRunning' at 5 minutes interval
[LN:715] INF: Observing /data/clips
StdErr: [LN:717] ERR: Skipping path '/data/clips' because it does not exist!!!
[LN:715] INF: Observing /data/movie
StdErr: [LN:717] ERR: Skipping path '/data/movie' because it does not exist!!!
[LN:753] INF: Waiting for a file change-trigger. Timeout = 60 seconds.
[LN:753] INF: Waiting for a file change-trigger. Timeout = 60 seconds.
```

I realize my compose is calling "/media/video/adult:/data" but within the container I'm referencing "/media/video/adult/clips" & /media/video/adult/movies", and withing stash "/data/clips" & "/data/movie" are used paths. 

Stash is working great, these bind mounts for the filemonitor are not, since it's skipping the paths- not really sure how to get the paths to match up the way they should without completely re-configuring stash. 

### What Operating System (OS)?

Arch Linux

### What browser and version?

Firefox 135.0

### Snapshot(s)

![Image](https://github.com/user-attachments/assets/1d50c343-c3e2-4d4b-bcbe-f9b03e01d54d)
